services:
  sourcery-qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: sourcery-qdrant
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - ${QDRANT_PORT_1:-6333}:6333
      - ${QDRANT_PORT_2:-6334}:6334
    volumes:
      - ./data/qdrant_data:/qdrant/storage

  sourcery-redis:
    image: redis:latest
    restart: always
    container_name: sourcery-redis
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - ${REDIS_PORT:-6379}:6379
    volumes:
        - ./data/redis:/data

  sourcery-ollama:
    image: ollama/ollama:latest
    restart: always
    container_name: sourcery-ollama
    ports:
      - ${OLLAMA_PORT:-11435}:11434
    volumes:
      - ./data/ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=${OLLAMA_NUM_PARALLEL:-1}
      - OLLAMA_KEEP_ALIVE=${OLLAMA_KEEP_ALIVE:-5}
    healthcheck:
      test: ollama --version || exit 1
      interval: 30s
      timeout: 3s
      retries: 5
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${NVIDIA_DRIVER:-nvidia}
              count: ${OLLAMA_GPU_COUNT:-1}
              capabilities: ["${NVIDIA_CAPABILITIES:-gpu}"]
  
  sourcery-reranking:
    image: jasony/document-reranking-api:latest
    restart: always
    container_name: sourcery-reranking
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${NVIDIA_DRIVER:-nvidia}
              count: ${RERANKING_GPU_COUNT:-1}
              capabilities: ["${NVIDIA_CAPABILITIES:-gpu}"]

  sourcery:
    build:
      dockerfile: Dockerfile
    tty: true
    restart: always
    container_name: sourcery
    ports:
      - ${SOURCERY_PORT:-9000}:9000
      - ${SOURCERY_WEBSOCKET_PORT:-9001}:9001
    volumes:
      - ./data/projects:/var/lib/sourcery/projects
      - ./packages:/app/packages
      - ./data/models:/models
    env_file:
      - .env
    environment:
      - PROJECT_DIR=/var/lib/sourcery/projects
      - OLLAMA_URL=http://sourcery-ollama:11434
      - QDRANT_URL=http://sourcery-qdrant:6333
      - REDIS_HOST=sourcery-redis
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://sourcery-mongodb:27017
      - WEBSOCKET_PORT=9001
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: ${NVIDIA_DRIVER:-nvidia}
              count: ${SOURCERY_GPU_COUNT:-1}
              capabilities: ["${NVIDIA_CAPABILITIES:-gpu}"]

  sourcery-mongodb:
    image: mongo:latest
    restart: always
    container_name: sourcery-mongodb
    ports:
      - ${MONGODB_PORT:-27017}:27017
    volumes:
      - ./data/mongodb:/data/db

  sourcery-ner:
    image: jasony/sourcery-ner-api:latest
    restart: always
    container_name: sourcery-ner

  sourcery-mailhog:
    image: mailhog/mailhog:latest
    restart: always
    container_name: sourcery-mailhog
    ports:
      # - 1025:1025
      - ${MAILHOG_PORT:-8026}:8025
