services:
  sourcery-qdrant:
    image: qdrant/qdrant:latest
    restart: always
    container_name: sourcery-qdrant
    healthcheck:
      test: ["CMD-SHELL", "bash -c ':> /dev/tcp/127.0.0.1/6333' || exit 1"]
      interval: 30s
      timeout: 5s
      retries: 5
      start_period: 30s
    ports:
      - 6333:6333
      - 6334:6334
    volumes:
      - ./data/qdrant_data:/qdrant/storage

  sourcery-keydb:
    # image: eqalpha/keydb:latest
    image: redis:latest
    restart: always
    container_name: sourcery-keydb
    healthcheck:
      test: ["CMD-SHELL", "redis-cli ping | grep PONG"]
      interval: 10s
      timeout: 3s
      retries: 5
    ports:
      - 6379:6379
    volumes:
      - ./data/keydb_data:/data

  sourcery-ollama:
    image: ollama/ollama:latest
    restart: always
    container_name: sourcery-ollama
    ports:
      - 11435:11434
    volumes:
      - ./data/ollama:/root/.ollama
    environment:
      - OLLAMA_NUM_PARALLEL=1
      - OLLAMA_KEEP_ALIVE=5
    healthcheck:
      test: ollama --version || exit 1
      interval: 30s
      timeout: 3s
      retries: 5
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]
  
  sourcery-reranking:
    image: jasony/document-reranking-api:latest
    restart: always
    container_name: sourcery-reranking
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 2
              capabilities: [gpu]

  sourcery:
    build:
      dockerfile: Dockerfile
    tty: true
    restart: always
    container_name: sourcery
    ports:
      - 9000:9000
    volumes:
      - ./data/projects:/var/lib/sourcery/projects
      - ./packages:/app/packages
      - ./data/models:/models
    env_file:
      - .env
    environment:
      - PROJECT_DIR=/var/lib/sourcery/projects
      - OLLAMA_URL=http://sourcery-ollama:11434
      - QDRANT_URL=http://sourcery-qdrant:6333
      - REDIS_HOST=sourcery-keydb
      - REDIS_PORT=6379
      - MONGO_URL=mongodb://sourcery-mongodb:27017
    privileged: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]

  sourcery-mongodb:
    image: mongo:latest
    restart: always
    container_name: sourcery-mongodb
    ports:
      - 27017:27017
    volumes:
      - ./data/mongodb:/data/db

  # sourcery-ws:
  #   image: jasony/ws-subscribe-broadcast:latest
  #   restart: always
  #   container_name: sourcery-ws
  #   ports:
  #     - 9001:3000

  sourcery-ws:
    build:
      context: .
      dockerfile: packages/sourcery-ws/Dockerfile
    restart: always
    container_name: sourcery-ws
    ports:
      - 9001:3001
    volumes:
      - ./packages/sourcery-ws:/app/packages/sourcery-ws
      - ./packages/sourcery-queue:/app/packages/sourcery-queue
    environment:
      - REDIS_HOST=sourcery-keydb
      - REDIS_PORT=6379

  sourcery-ner:
    image: jasony/sourcery-ner-api:latest
    restart: always
    container_name: sourcery-ner

  sourcery-mailhog:
    image: mailhog/mailhog:latest
    restart: always
    container_name: sourcery-mailhog
    ports:
      # - 1025:1025
      - 8026:8025
