// Copyright (C) 2025 Jason Norwood-Young
// 
// This program is free software: you can redistribute it and/or modify
// it under the terms of the GNU Affero General Public License as
// published by the Free Software Foundation, either version 3 of the
// License, or (at your option) any later version.
// 
// This program is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
// GNU Affero General Public License for more details.
// 
// You should have received a copy of the GNU Affero General Public License
// along with this program.  If not, see <https://www.gnu.org/licenses/>.

import { z } from 'zod';
import { zfd } from 'zod-form-data';

export const keyNameMap = {
    'admin_email': {
        'name': 'Admin Email',
        'type': 'email',
        'placeholder': 'admin@example.com',
        'required': true,
        'default': '',
        'description': 'The email address of the admin.',
        'category': 'System',
        'dotenv': 'ADMIN_EMAIL',
        'schema': zfd.text(z.string().optional()),
    },
    'smtp_host': {
        'name': 'SMTP Host',
        'type': 'text',
        'placeholder': 'smtp.example.com',
        'required': false,
        'default': '',
        'description': 'The host of the SMTP server.',
        'category': 'Email',
        'dotenv': 'SMTP_HOST',
        'schema': zfd.text(z.string().optional()),
    },
    'smtp_port': {
        'name': 'SMTP Port',
        'type': 'number',
        'placeholder': '587',
        'required': false,
        'default': '587',
        'description': 'The port of the SMTP server.',
        'category': 'Email',
        'dotenv': 'SMTP_PORT',
        'schema': zfd.numeric(z.number().optional()),
    },
    'smtp_user': {
        'name': 'SMTP User',
        'type': 'text',
        'placeholder': 'user@example.com',
        'required': false,
        'default': '',
        'description': 'The username of the SMTP server.',
        'category': 'Email',
        'dotenv': 'SMTP_USER',
        'schema': zfd.text(z.string().optional()),
    },
    'smtp_password': {
        'name': 'SMTP Password',
        'type': 'password',
        'placeholder': 'password',
        'required': false,
        'default': '',
        'description': 'The password of the SMTP server.',
        'category': 'Email',
        'dotenv': 'SMTP_PASSWORD',
        'schema': zfd.text(z.string().optional()),
    },
    'smtp_from_email': {
        'name': 'SMTP From Email',
        'type': 'email',
        'placeholder': 'user@example.com',
        'required': false,
        'default': '',
        'description': 'The email address of the sender.',
        'category': 'Email',
        'dotenv': 'SMTP_FROM_EMAIL',
        'schema': zfd.text(z.string().optional()),
    },
    'smtp_from_name': {
        'name': 'SMTP From Name',
        'type': 'text',
        'placeholder': 'Sourcery',
        'required': false,
        'default': 'Sourcery',
        'description': 'The name of the sender.',
        'category': 'Email',
        'dotenv': 'SMTP_FROM_NAME',
        'schema': zfd.text(z.string().optional()),
    },
    'ollama_url': {
        'name': 'Ollama URL',
        'type': 'text',
        'placeholder': 'http://localhost:11434',
        'required': false,
        'default': 'http://localhost:11434',
        'description': 'The URL of the Ollama server.',
        'category': 'Ollama',
        'dotenv': 'OLLAMA_URL',
        'schema': zfd.text(z.string().optional()),
    },
    'mongo_url': {
        'name': 'MongoDB URL',
        'type': 'text',
        'placeholder': 'mongodb://localhost:27017/sourcery',
        'required': true,
        'default': 'mongodb://localhost:27017/sourcery',
        'description': 'The URI of the MongoDB server.',
        'category': 'Database',
        'dotenv': 'MONGO_URL',
        'schema': zfd.text(z.string().optional()),
    },
    'qdrant_url': {
        'name': 'Qdrant URL',
        'type': 'text',
        'placeholder': 'http://localhost:6333',
        'required': true,
        'default': 'http://localhost:6333',
        'description': 'The URL of the Qdrant server.',
        'category': 'Database',
        'dotenv': 'QDRANT_URL',
        'schema': zfd.text(z.string().optional()),
    },
    'redis_host': {
        'name': 'Redis Host',
        'type': 'text',
        'placeholder': 'localhost',
        'required': true,
        'default': 'localhost',
        'description': 'The host of the Redis server.',
        'category': 'Database',
        'dotenv': 'REDIS_HOST',
        'schema': zfd.text(z.string().optional()),
    },
    'redis_password': {
        'name': 'Redis Password',
        'type': 'password',
        'placeholder': 'password',
        'required': false,
        'default': '',
        'description': 'The password of the Redis server.',
        'category': 'Database',
        'dotenv': 'REDIS_PASSWORD',
        'schema': zfd.text(z.string().optional()),
    },
    'redis_port': {
        'name': 'Redis Port',
        'type': 'number',
        'placeholder': '6379',
        'required': true,
        'default': '6379',
        'description': 'The port of the Redis server.',
        'category': 'Database',
        'dotenv': 'REDIS_PORT',
        'schema': zfd.numeric(z.number().optional()),
    },
    'project_dir': {
        'name': 'Project Directory',
        'type': 'text',
        'placeholder': '/var/lib/sourcery/projects',
        'required': true,
        'default': '/var/lib/sourcery/projects',
        'description': 'The directory where the projects are stored.',
        'category': 'System',
        'dotenv': 'PROJECT_DIR',
        'schema': zfd.text(z.string().optional()),
    },
    'site_url': {
        'name': 'Site URL',
        'type': 'text',
        'placeholder': 'https://sourcery.example.com',
        'required': true,
        'default': '',
        'description': 'The URL of the site.',
        'category': 'System',
        'dotenv': 'ORIGIN',
        'schema': zfd.text(z.string().optional()),
    }
}